name: Docker build and publish

on:
  push:
    branches: [develop-fork]
  pull_request:
    branches: [develop-fork]

  workflow_dispatch:

jobs:
  docker-build-publish:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx

      - uses: FranzDiebold/github-env-vars-action@v2

      - name: Image name
        id: get_image_name
        run: echo "::set-output name=image_name::${CI_HEAD_REF_SLUG}"

      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: ${{ secrets.DOCKERHUB_ORG }}/3dfav2:${{ steps.get_image_name.outputs.image_name }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
